/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ydwiv
 */
import java.awt.*;
public class tictac extends javax.swing.JFrame {
String	v1in;
int vv1;
int counter=1;
String v2in;
int vv2;
String v3in;
int vv3;
String v4in;
int vv4;
String v5in;
int vv5;
String v6in;
int vv6;
String v7in;
int vv7;
String v8in;
int vv8;
String v9in;
int vv9;


    /**
     * Creates new form tictac
     */
    public tictac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        v1 = new javax.swing.JButton();
        v9 = new javax.swing.JButton();
        v3 = new javax.swing.JButton();
        v4 = new javax.swing.JButton();
        v6 = new javax.swing.JButton();
        v7 = new javax.swing.JButton();
        v8 = new javax.swing.JButton();
        v2 = new javax.swing.JButton();
        v5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        
        v1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v1MouseClicked(evt);
            }
        });
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

       
        v9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v9MouseClicked(evt);
            }
        });

        
        v3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v3MouseClicked(evt);
            }
        });

        
        v4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v4MouseClicked(evt);
            }
        });
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });


        v6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v6MouseClicked(evt);
            }
        });
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });

        v7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v7MouseClicked(evt);
            }
        });


        v8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v8MouseClicked(evt);
            }
        });
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });


        v2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v2MouseClicked(evt);
            }
        });
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });


        v5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v5MouseClicked(evt);
            }
        });
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(v4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(v1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(v5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(v2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v9, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(v3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(v4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(v6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(v8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        


                                

    private void v1MouseClicked(java.awt.event.MouseEvent evt) {                                
        if(vv1==0){if(counter%2==1)
        {v1in="RED";
        v1.setBackground(Color.red);
        counter++;
        check(counter%2,v1in);
		vv1++;}
        else if(counter%2==0)
        {v1.setBackground(Color.blue);
        v1in="BLUE";
        counter++;
        check(counter%2,v1in);
		vv1++;}}
    }                               

    private void v2MouseClicked(java.awt.event.MouseEvent evt) {                                
		if(vv2==0){ if(counter%2==1)
        {v2in="RED";
        v2.setBackground(Color.red);
        counter++;
        check(counter%2,v2in);
		vv2++;}
        else if(counter%2==0)
        {v2.setBackground(Color.blue);
        v2in="BLUE";
        counter++;
        check(counter%2,v2in);
		vv2++;
	}}
    }                               

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void v3MouseClicked(java.awt.event.MouseEvent evt) {                                
       if(vv3==0){ if(counter%2==1)
        {v3in="RED";
        v3.setBackground(Color.red);
        counter++;
        check(counter%2,v3in);
		vv3++;}
        else if(counter%2==0)
        {v3.setBackground(Color.blue);
        v3in="BLUE";
        counter++;
        check(counter%2,v3in);
	   vv3++;}}
    }                               

    private void v4MouseClicked(java.awt.event.MouseEvent evt) {                                
        if(vv4==0){if(counter%2==1)
        {v4in="RED";
        v4.setBackground(Color.red);
        counter++;
        check(counter%2,v4in);
		vv4++;}
        else if(counter%2==0)
        {v4.setBackground(Color.blue);
        v4in="BLUE";
        counter++;
        check(counter%2,v4in);
		vv4++;}}
    }                               
private void v1ActionPerformed(java.awt.event.ActionEvent evt)
{
	
}
    private void v5MouseClicked(java.awt.event.MouseEvent evt) {                                
        if(vv5==0){if(counter%2==1)
        {v5in="RED";
        v5.setBackground(Color.red);
        counter++;
        check(counter%2,v5in);
		vv5++;}
        else if(counter%2==0)
        {v5.setBackground(Color.blue);
        v5in="BLUE";
        counter++;
        check(counter%2,v5in);
		vv5++;}}
    }                               
private void v4ActionPerformed(java.awt.event.ActionEvent evt){}
    private void v6MouseClicked(java.awt.event.MouseEvent evt) {                                
		if(vv6==0){if(counter%2==1)
        {v6in="RED";
        v6.setBackground(Color.red);
        counter++;
        check(counter%2,v6in);
		vv6++;}
        else if(counter%2==0)
        {v6.setBackground(Color.blue);
        v6in="BLUE";
        counter++;
        check(counter%2,v6in);
		vv6++;}}
    }                               
private void v6ActionPerformed(java.awt.event.ActionEvent evt){}
    private void v7MouseClicked(java.awt.event.MouseEvent evt) {                                
        if(vv7==0){if(counter%2==1)
        {v7in="RED";
        v7.setBackground(Color.red);
        counter++;
        check(counter%2,v7in);
		vv7++;}
        else if(counter%2==0)
        {v7.setBackground(Color.blue);
        v7in="BLUE";
        counter++;
        check(counter%2,v7in);
		vv7++;}}
    }                               
private void v8ActionPerformed(java.awt.event.ActionEvent evt){}
    private void v8MouseClicked(java.awt.event.MouseEvent evt) {                                
       if(vv8==0)
	   {if(counter%2==1)
        {v8in="RED";
        v8.setBackground(Color.red);
        counter++;
		vv8++;
        check(counter%2,v8in);}
        else if(counter%2==0)
        {v8.setBackground(Color.blue);
        v8in="BLUE";
        counter++;
		vv8++;
		check(counter%2,v8in);}
	}
    }                               
private void v5ActionPerformed(java.awt.event.ActionEvent evt){}	
    private void v9MouseClicked(java.awt.event.MouseEvent evt) {                                
       if(vv9==0)
		{if(counter%2==1)
        {v9in="RED";
        v9.setBackground(Color.red);
        counter++;
	vv9++;
        check(counter%2,v9in);}
        else if(counter%2==0)
        {v9.setBackground(Color.blue);
        v1in="BLUE";
	vv9++;
        counter++;
        check(counter%2,v9in);}
		}
    }                                                    
    public void check(int pla,String in)
    {
        if(v1in==in && v2in==in && v3in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
		System.out.println("PLAYER "+in+" WON THE MATCH");
		
}
        else if(v4in==in && v5in==in && v6in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		
}
        else if(v7in==in && v8in==in && v9in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		
}
        else if(v1in==in && v4in==in && v7in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		
		}
        else if(v2in==in && v5in==in && v8in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		}
        else if(v3in==in && v6in==in && v9in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	
	}
        else if(v1in==in && v5in==in && v9in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		
		}
        else if(v3in==in && v5in==in && v7in==in)
        {t1.setText("PLAYER "+in+" WON THE MATCH");
	System.out.println("PLAYER "+in+" WON THE MATCH");
		
		}
		else if(counter==10)
		{t1.setText("DRAW MATCH");
	System.out.println("DRAW MATCH");
		
	}

        
        
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t1;
    private javax.swing.JButton v1;
    private javax.swing.JButton v2;
    private javax.swing.JButton v3;
    private javax.swing.JButton v4;
    private javax.swing.JButton v5;
    private javax.swing.JButton v6;
    private javax.swing.JButton v7;
    private javax.swing.JButton v8;
    private javax.swing.JButton v9;
    // End of variables declaration                   
}





